# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ce92b4aac43d295850d8fc8a4cf66bae0d00a714d2265245d3aa77e5edd17b983908cbb5252789a52e0d7da6bdbfd6c7b332f959ac00738c0bcd4e0cc67aa5

test:
  secret_key_base: 54738a3bcc593382871b6adac717d15144ba42579365b52ad0a752e5557d1e58b56ddd6a5fb8810b1de6b9f59e4ae36a714f41b794b15f38de6f0c2bb380ac92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
